mysite/blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

admin.autodiscover()
app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.tag, name='tag'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^archives/$', views.ArchiveListView.as_view(), name='archive_list'),
    url(r'^tags/$', views.TagsView.as_view(), name='tag_list'),
    url(r'^friends/$', views.FriendsView.as_view(), name='friends')
]

mysite/comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'

urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comments'),
]

mysite/blog/models.py
import markdown
import re
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User, UserManager
from django.urls import reverse
from django.utils.html import strip_tags

# 拓展用户模型，增加avatar字段，description字段
class UserProfile(models.Model):
    user = models.OneToOneField(User, verbose_name='用户')
    avatar = models.ImageField(default="/media/uploads/avatar/avatar.jpg", verbose_name='头像')
    description = models.TextField(max_length=200, verbose_name='个人简介')

    objects = UserManager()

    # 默认返回用户的名字
    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

class Tag(models.Model):
    name = models.CharField(max_length=100)
    thumb = models.ImageField(default='/media/uploads/images/pic05.jpg', verbose_name='图标')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

class Post(models.Model):

    #文章标题
    title = models.CharField(max_length=100, verbose_name='标题')

    #文章正文
    body = RichTextUploadingField(verbose_name='正文')

    #创建时间和最后一次修改时间
    create_time = models.DateTimeField(verbose_name='创建时间')
    modified_time = models.DateTimeField(verbose_name='修改时间')

    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField(max_length=200, blank=True, verbose_name='摘要')

    # 缩略图
    thumb = models.ImageField(verbose_name='缩略图', upload_to='uploads/%Y/%m/%d', blank=True)

    # 这是分类与标签，分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一对多的关联关系。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 ManyToManyField，表明这是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
    # 如果你对 ForeignKey、ManyToManyField 不了解，请看教程中的解释，亦可参考官方文档：
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
    category = models.ForeignKey(Category, verbose_name='分类')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='标签')

    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    author = models.ForeignKey(UserProfile, verbose_name='作者')

    #新增view字段记录阅读量PV
    views = models.PositiveIntegerField(default=0, verbose_name='浏览量')

    #字数统计
    word_count = models.IntegerField(default=0, verbose_name='字数统计')

    def __str__(self):
        return self.title

    # 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):

        # 首先实例化一个markdown类，用于渲染body的文本
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

        #如果没有填写摘要
        if not self.excerpt:
            #strip_tag去掉HTML文本的全部HTML标签
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        # 如果当前文章传了图片，那么取第一张图作为本章的缩略图
        try:
            img = re.findall('<img src="(.*?)"', self.body)[0]
            self.thumb = img[6:]
        except:
            # 如果没找到图片，就啥也不做
            pass


        # 统计字数
        self.word_count = len(strip_tags(md.convert(self.body)))

        #调用父类的 save 方法将数据保存在数据库中
        super(Post, self).save(*args, **kwargs)

    #Django 允许我们在 models.Model 的子类里定义一个 Meta 的内部类，这个内部类通过指定一些属性来规定这个类该有的一些特性，例如在这里我们要指定 Post 的排序方式。
    class Meta:
        ordering = ['-create_time']
        verbose_name = '文章'
        verbose_name_plural = verbose_name

#关于
class About(models.Model):
    # 标题
    title = models.CharField(max_length=200, verbose_name="标题")
    # 主体内容
    body = RichTextUploadingField(verbose_name='正文')
    create_time = models.DateTimeField(verbose_name="发布日期")
    modified_time = models.DateTimeField(verbose_name="修改日期")
    veiws = models.PositiveIntegerField(default=0, verbose_name="访问量")
    avatar = models.ImageField(blank=True, verbose_name="头像", upload_to="uploads/avatar")
    class Meta:
        verbose_name = '关于'
        verbose_name_plural = verbose_name
        ordering = ['-create_time']

    def increase_views(self):
        #更薪访问量
        self.veiws += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

#友情链接
class FriendSites(models.Model):
    """
    友情链接
    """
    site_name = models.CharField(max_length=20, blank=False, verbose_name='站点名称')
    site_intro = models.TextField(default='没有填写简介', verbose_name='简介')
    site_url = models.URLField(blank=False, max_length=200, verbose_name='链接')
    admin_name = models.CharField(max_length=30, verbose_name='站长名称')
    admin_contact = models.CharField(max_length=200, verbose_name='站长联系方式')
    create_time = models.DateTimeField(verbose_name='创建时间')
    modified_time = models.DateTimeField(verbose_name='修改时间')
    site_thumb = models.ImageField(blank=True, verbose_name="缩略图")

    def __str__(self):
        return self.site_name

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name
        ordering = ['-create_time']  #排序


#访问记录
class VisitorRecord(models.Model):
    """
    记录游客的访问记录
    """
    http_host = models.CharField(max_length=200, verbose_name="主机")
    http_path = models.CharField(max_length=200, verbose_name="地址")
    http_user_agent = models.CharField(max_length=400, verbose_name="客户端信息")
    ip = models.CharField(max_length=30, verbose_name="IP")
    server_name = models.CharField(max_length=50, verbose_name="服务器主机名")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="请求时间")

    class Meta:
        verbose_name = "访问记录"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ip


#站点运营统计数据，每天的有效访问量，访问ip等
class PageView(models.Model):
    """
    记录站点的运营统计数据, 每天的有效访问量以及IP
    """
    today_visit = models.PositiveIntegerField(default=0, verbose_name="访问量")
    today_pv = models.PositiveIntegerField(default=0, verbose_name="今日pv")
    create_date = models.DateField(unique=True, editable=True, verbose_name="日期")

    class Meta:
        verbose_name = "运营统计"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "%s 访问量" % self.create_date.strftime('%Y-%m-%d')

mysite/comments/models.py
from django.db import models

class Comment(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

mysite/templates/oldTemplate/about.html
{% extends 'base.html' %}
{% block main %}
	{% load static %}
	{% for v in post %}
	<h1 class="page-title">{{v.title}}</h1>
	<article class="post">
		<div class="entry-content clearfix">
			<figure class="img-responsive-center">
				<img class="img-responsive" src="{{v.avatar.url}}" alt="Developer Image">
			</figure>
			<p>{{v.body|safe}}</p>
			<div class="height-40px"></div>
			<h2 class="title text-center">Social</h2>
			<ul class="social">
				<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
				<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
				<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
				<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
			</ul>
		</div>
	</article>
	{% endfor %}
{% endblock main %}

mysite/templates/oldTemplate/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Nearw的博客</title>
    {% load static %}
    {% load blog_tags %}
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlights/manni.css' %}">
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Nearw</b>的博客</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}

                {% get_recent_posts as recent_post_list %}

                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        {% for post in recent_post_list %}
                            <li>
                                <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                            </li>
                        {% empty %}
                            <li>暂无文章</li>
                        {% endfor %}
                    </ul>
                </div>
                {% archives as date_list %}
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% for date in date_list %}
                            <li>
                                <a href="{% url 'blog:archives' date.year date.month %}">{{date.year}} 年 {{date.month}} 月</a>
                            </li>
                        {% empty %}
                            <li>暂无归档</li>
                        {% endfor %}
                    </ul>
                </div>
                {% get_categories as category_list %}
                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:category' category.pk %}">{{category.name}}
                                    <span class="post-count">({{category.num_posts}})</span>
                                </a>
                            </li>
                        {% empty %}
                            <li>暂无分类</li>
                        {% endfor %}
                    </ul>
                </div>
                {% get_tags as tag_list %}
                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% for tag in tag_list %}
                            <li>
                                <a href="{% url 'blog:tag' tag.pk %}">{{tag.name}}</a>
                                <span>{{tag.num_post}}</span>
                            </li>
                        {% empty %}
                            <li>
                                暂无标签
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="https://123.56.26.224" title="网页模板" target="_blank">刘祥麟</a>修改
                </p>
            </div>
            <div class="page-view-static">
                <p>网站已运行: {% get_all_run_day %} 天</p>
                {% get_all_visit_count as total_count %}
                <p>总访问量: {{total_count.total_visit}} | 今日访问量: {% get_today_visit_count %}</p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="{% url 'blog:index' %}">博客</a></li>
            <li><a href="{% url 'blog:about' %}">关于</a></li>
            <li><a href="{% url 'blog:contact' %}">联系</a></li>
        </ul>
    </nav>
</div>

<!-- js -->
<script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/pace.min.js' %}"></script>
<script src="{% static 'js/modernizr.custom.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

mysite/templates/oldTemplate/contact.html
{% extends 'base.html' %}
{% block main %}
	<h1 class="page-title">联系我</h1>
	<article class="post">
		<div class="entry-content clearfix">
			<form action="#" method="post" class="contact-form">
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<input type="text" name="name" placeholder="Name" required>
						<input type="email" name="email" placeholder="Email" required>
						<input type="text" name="subject" placeholder="Subject" required>
						<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
						<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
					</div>
				</div>	<!-- row -->
			</form>
		</div>
	</article>
{% endblock main %}

mysite/templates/oldTemplate/index-preversion.html
{% extends 'base.html' %}
{% block main %}
    {% for post in post_list %}
        <article class="post post-{{post.pk}}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{post.category.name}}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{post.create_time}}">{{post.create_time}}</time></a></span>
                    <span class="post-author"><a href="#">{{post.author}}</a></span>
                    <span class="comments-link"><a href="#">{{post.comment_set.count}} 评论</a></span>
                    <span class="views-count"><a href="#">{{post.views}} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{post.excerpt}}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{post.get_absolute_url}}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <div class="pagination">
        <ul>
            <li class="current"><a href="">1</a></li>
            <li><a href="">2</a></li>
        </ul>
    </div>
{% endblock main %}

mysite/templates/oldTemplate/index-side.html
<!DOCTYPE HTML>
<html>
{% load static blog_tags %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>刘祥麟的博客</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by freehtml5.co"/>
    <meta name="keywords"
          content="博客 blog 个人网站 templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive, 湖南, 浏阳"/>
    <meta name="author" content="刘祥麟"/>
    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content=""/>
    <meta name="twitter:image" content=""/>
    <meta name="twitter:url" content=""/>
    <meta name="twitter:card" content=""/>

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">
    <!-- Animate.css -->
    <link rel="stylesheet" href="{% static 'blog/css/animate.css' %}">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="{% static 'blog/css/icomoon.css' %}">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">

    <!-- Theme style  -->
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">

    <!-- Modernizr JS -->
    <script src="{% static 'blog/js/modernizr-2.6.2.min.js' %}"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="{% static 'blog/js/respond.min.js' %}"></script>
    <![endif]-->

</head>
<body>

<div class="fh5co-loader"></div>

<!--modal-->
<div id="mask" class="mask fade">
    <div class="dialog category-class">
        {% archives as date_list %}
        <ul class="archives">
            {% for date in date_list %}
            <li>
                <a href="{% url 'blog:archives' date.year date.month %}">{{date.year}}年{{date.month}}月</a>
            </li>
            {% endfor %}
        </ul>
        <div class="footer">
            <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-remove"></span>
            </button>
        </div>
    </div>
    <div class="dialog category-class">
        {% get_categories as category_list %}
        <ul class="tag-list">
            {% for category in category_list %}
            <li><a href="{% url 'blog:category' category.pk %}">{{category.name}}({{category.num_posts}})</a></li>
            {% endfor %}
        </ul>
        <div class="footer">
            <button type="button" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </div>
    </div>
    <div class="dialog category-class">
        {% get_tags as tags_list %}
        <ul class="tag-list">
            {% for tag in tags_list %}
            <li><a href="{% url 'blog:tag' tag.pk %}">{{tag.name}}({{tag.num_post}})</a></li>
            {% endfor %}
        </ul>
        <div class="footer">
            <button type="button" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </div>
    </div>
</div>
<div id="page">
    <div id="fh5co-aside" style="background-image: url({% static 'blog/img/image_1.jpg' %})">
        <div class="overlay"></div>
        <div class="header">
            <img src="{% static 'blog/img/person_3.jpg' %}" alt="">
        </div>
        <h1 class="blog-name">Nearw 的博客</h1>
        <div class="aside">
            <a href="javascript:void(0);">最新文章</a>
            {% get_recent_posts as recent_list %}
            <ul>
                {% for post in recent_list %}
                <li><a href="{{post.get_absolute_url}}">{{post.title}}</a></li>
                {% endfor %}
            </ul>
            <a href="#" class="tag">归档</a>
            <a href="#" class="tag">分类</a>
            <a href="#" class="tag">标签</a>
        </div>
        <div class="featured">
            <a href="{% url 'blog:about' %}"><span>关于我</span></a>
        </div>
    </div>
    <div id="fh5co-main-content">
        <div class="fh5co-post">
            {% if error_msg %}
                <p>{{error_msg}}</p>
            {% endif %}
            {% for post in post_list %}
            <div class="fh5co-entry padding">
                <img src="{{post.thumb.url}}" alt="">
                <div>
                    <span class="fh5co-post-date">{{post.create_time}}</span>
                    <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
                    <p>{{post.excerpt | safe}}</p>
                </div>
            </div>
            {% empty %}
                <div class="no-post">暂时还没有发布的文章！</div>
            {% endfor %}
            {% if is_paginated %}
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if first %}
                            <li>
                                <a href="?page=1" aria-label="Previous">
                                    <span aria-hidden="true">1</span>
                                </a>
                            </li>
                        {% endif %}
                        {% if left %}
                            {% if left_has_more %}
                                <li><a href="">···</a></li>
                            {% endif %}
                            {% for i in left %}
                                <li><a href="?page={{i}}">{{i}}</a></li>
                            {% endfor %}
                        {% endif %}
                        <li class="active"><a href="?page={{page_obj.number}}">{{page_obj.number}}</a></li>
                        {% if right %}
                            {% for i in right %}
                                <li><a href="?page={{i}}">{{i}}</a></li>
                            {% endfor %}
                            {% if right_has_more %}
                                <li><a href="">···</a></li>
                            {% endif %}
                        {% endif %}
                        {% if last %}
                            <li>
                                <a href="?page={{paginator.num_pages}}" aria-label="Next">
                                    <span aria-hidden="true">{{paginator.num_pages}}</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
            <footer>
                <div class="copyright">
                    &copy; 2016 Free HTML5. All Rights Reserved. More Templates <a href="http://www.cssmoban.com/"
                                                                                   target="_blank" title="模板之家">模板之家</a>
                    - 由 <a href="http://123.56.26.224/" title="网页模板" target="_blank">刘祥麟的博客</a>修改
                </div>

                <div class="page-view-static">
                    <p>网站已运行: {% get_all_run_day %} 天</p>
                    {% get_all_visit_count as total_count %}
                    <p>总访问量: {{total_count.total_visit}} | 今日访问量: {% get_today_visit_count %}</p>
                </div>
                <div class="beian">
                    <h5><a href="http://www.miibeian.gov.cn">湘ICP备 17013572号</a></h5>
                </div>
            </footer>
        </div>
    </div>
</div>

<div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
</div>

<!-- jQuery -->
<script src="{% static 'blog/js/jquery.min.js' %}"></script>
<!-- jQuery Easing -->
<script src="{% static 'blog/js/jquery.easing.1.3.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'blog/js/jquery.waypoints.min.js' %}"></script>
<!-- Stellar Parallax -->
<script src="{% static 'blog/js/jquery.stellar.min.js' %}"></script>
<!-- Main -->
<script src="{% static 'blog/js/main.js' %}"></script>
<script>
    var $mask = $("#mask"),
        $dialog = $(".dialog");
    $(".tag").click(function () {
        console.log($(this))
        $mask.show(200).addClass('in');
        $dialog.eq($(this).index(".tag")).fadeIn();
    })
    $(".btn").click(function () {
        $mask.removeClass("in").hide(300);
        $(this).parents(".dialog").hide();
    })
</script>
</body>
</html>