mysite/blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

admin.autodiscover()
app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.tag, name='tag'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^archives/$', views.ArchiveListView.as_view(), name='archive_list'),
    url(r'^tags/$', views.TagsView.as_view(), name='tag_list'),
    url(r'^friends/$', views.FriendsView.as_view(), name='friends')
]

mysite/blog/models.py
import markdown
import re
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User, UserManager
from django.urls import reverse
from django.utils.html import strip_tags

# 拓展用户模型，增加avatar字段，description字段
class UserProfile(models.Model):
    user = models.OneToOneField(User, verbose_name='用户')
    avatar = models.ImageField(default="/media/uploads/avatar/avatar.jpg", verbose_name='头像')
    description = models.TextField(max_length=200, verbose_name='个人简介')

    objects = UserManager()

    # 默认返回用户的名字
    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

class Tag(models.Model):
    name = models.CharField(max_length=100)
    thumb = models.ImageField(default='/media/uploads/images/pic05.jpg', verbose_name='图标')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

class Post(models.Model):

    #文章标题
    title = models.CharField(max_length=100, verbose_name='标题')

    #文章正文
    body = RichTextUploadingField(verbose_name='正文')

    #创建时间和最后一次修改时间
    create_time = models.DateTimeField(verbose_name='创建时间')
    modified_time = models.DateTimeField(verbose_name='修改时间')

    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField(max_length=200, blank=True, verbose_name='摘要')

    # 缩略图
    thumb = models.ImageField(verbose_name='缩略图', upload_to='uploads/%Y/%m/%d', blank=True)

    # 这是分类与标签，分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一对多的关联关系。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 ManyToManyField，表明这是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
    # 如果你对 ForeignKey、ManyToManyField 不了解，请看教程中的解释，亦可参考官方文档：
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
    category = models.ForeignKey(Category, verbose_name='分类')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='标签')

    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    author = models.ForeignKey(UserProfile, verbose_name='作者')

    #新增view字段记录阅读量PV
    views = models.PositiveIntegerField(default=0, verbose_name='浏览量')

    #字数统计
    word_count = models.IntegerField(default=0, verbose_name='字数统计')

    def __str__(self):
        return self.title

    # 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):

        # 首先实例化一个markdown类，用于渲染body的文本
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

        #如果没有填写摘要
        if not self.excerpt:
            #strip_tag去掉HTML文本的全部HTML标签
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        # 如果当前文章传了图片，那么取第一张图作为本章的缩略图
        try:
            img = re.findall('<img src="(.*?)"', self.body)[0]
            self.thumb = img[6:]
        except:
            # 如果没找到图片，就啥也不做
            pass


        # 统计字数
        self.word_count = len(strip_tags(md.convert(self.body)))

        #调用父类的 save 方法将数据保存在数据库中
        super(Post, self).save(*args, **kwargs)

    #Django 允许我们在 models.Model 的子类里定义一个 Meta 的内部类，这个内部类通过指定一些属性来规定这个类该有的一些特性，例如在这里我们要指定 Post 的排序方式。
    class Meta:
        ordering = ['-create_time']
        verbose_name = '文章'
        verbose_name_plural = verbose_name

#关于
class About(models.Model):
    # 标题
    title = models.CharField(max_length=200, verbose_name="标题")
    # 主体内容
    body = RichTextUploadingField(verbose_name='正文')
    create_time = models.DateTimeField(verbose_name="发布日期")
    modified_time = models.DateTimeField(verbose_name="修改日期")
    veiws = models.PositiveIntegerField(default=0, verbose_name="访问量")
    avatar = models.ImageField(blank=True, verbose_name="头像", upload_to="uploads/avatar")
    class Meta:
        verbose_name = '关于'
        verbose_name_plural = verbose_name
        ordering = ['-create_time']

    def increase_views(self):
        #更薪访问量
        self.veiws += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

#友情链接
class FriendSites(models.Model):
    """
    友情链接
    """
    site_name = models.CharField(max_length=20, blank=False, verbose_name='站点名称')
    site_intro = models.TextField(default='没有填写简介', verbose_name='简介')
    site_url = models.URLField(blank=False, max_length=200, verbose_name='链接')
    admin_name = models.CharField(max_length=30, verbose_name='站长名称')
    admin_contact = models.CharField(max_length=200, verbose_name='站长联系方式')
    create_time = models.DateTimeField(verbose_name='创建时间')
    modified_time = models.DateTimeField(verbose_name='修改时间')
    site_thumb = models.ImageField(blank=True, verbose_name="缩略图")

    def __str__(self):
        return self.site_name

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name
        ordering = ['-create_time']  #排序


#访问记录
class VisitorRecord(models.Model):
    """
    记录游客的访问记录
    """
    http_host = models.CharField(max_length=200, verbose_name="主机")
    http_path = models.CharField(max_length=200, verbose_name="地址")
    http_user_agent = models.CharField(max_length=400, verbose_name="客户端信息")
    ip = models.CharField(max_length=30, verbose_name="IP")
    server_name = models.CharField(max_length=50, verbose_name="服务器主机名")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="请求时间")

    class Meta:
        verbose_name = "访问记录"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ip


#站点运营统计数据，每天的有效访问量，访问ip等
class PageView(models.Model):
    """
    记录站点的运营统计数据, 每天的有效访问量以及IP
    """
    today_visit = models.PositiveIntegerField(default=0, verbose_name="访问量")
    today_pv = models.PositiveIntegerField(default=0, verbose_name="今日pv")
    create_date = models.DateField(unique=True, editable=True, verbose_name="日期")

    class Meta:
        verbose_name = "运营统计"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "%s 访问量" % self.create_date.strftime('%Y-%m-%d')

mysite/blog/views.py
import markdown
import re
from django.shortcuts import render, get_object_or_404
from comments.forms import CommentFrom
from .models import Post, Category, Tag, About, FriendSites
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from collections import defaultdict
from django.db.models import Q
# Create your views here.



class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        #首先获得父类生成的传递给模板的字典
        context = super().get_context_data(**kwargs)
        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。

        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        #当前页右边连续的页码号， 初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        #获得当前请求的页码号
        page_number = page.number

        #获得分页之后的总数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range


        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            #如果最右边的页码数比总数-1还要小，说明右侧还有更多
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            #如果当前请求的是最后一页数据，那么右边的页就没有了
            #此时只需要获取当前页左边的连续页码号
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。

            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True

        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'page_number': page_number,
            'last': last,
        }

        return data

# 详情
class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()

        #试图必须返回成一个HttpResponse对象
        return response

    def get_object(self, queryset=None):
        #重写get_object方法是因为需要对post的body进行处理
        return super(PostDetailView, self).get_object(queryset=None)

    def get_context_data(self, **kwargs):
        # 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
        # 还要把评论表单、post 下的评论列表传递给模板。
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentFrom()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })

        return context


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    #被访问一次阅读量+1
    post.increase_views()

    post.body = markdown.Markdown(post.body, extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])

    form = CommentFrom()

    comment_list = post.comment_set.all()

    context = {
        'post': post,
        'form': form,
        'comment_list': comment_list
    }
    return render(request, 'blog/detail.html', context=context)

def archives(request, year, month):
    post_list = Post.objects.all().order_by('-create_time')
    data = []
    # 查资料是mysql的一个bug，所以这里手动处理一下
    for post in post_list:
        if str(post.create_time.year) == str(year) and str(post.create_time.month) == str(month):
            data.append(post)

    return render(request, 'blog/index.html', context={'post_list': data})

# 归档
class ArchiveListView(ListView):
    template_name = 'blog/archive.html'
    context_object_name = 'archive_list'

    def get_queryset(self):
        context = Post.objects.dates('create_time', 'month', order='DESC')
        data = defaultdict(list)
        for item in context:
            data[item.year].append(item)

        return dict(data)


# 分类
class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)

def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate)
    return render(request, 'blog/index.html', context={'post_list': post_list})

def tag(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    post_list = Post.objects.filter(tags=tag)
    return render(request, 'blog/index.html', context={'post_list': post_list})

# 标签视图函数
class TagsView(ListView):
    model = Tag
    template_name = 'blog/tags.html'
    context_object_name = 'tag_list'

# 友链
class FriendsView(ListView):
    model = FriendSites
    template_name = 'blog/friends.html'
    context_object_name = 'friends_list'

# 关于
def about(request):
    post = About.objects.all()
    # 如果有多篇文章

    return render(request, 'blog/about.html', context={'post_list': post})

def contact(request):
    return render(request, 'blog/contact.html', context={'contact': 'contact'})

def search(request):
    q = request.GET.get("q")
    error_msg = ''

    if not q:
        error_msg = '请输入关键词'
        return render(request, 'blog/index.html', {'error_msg': error_msg})

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'error_msg': error_msg, 'post_list': post_list})

def page_not_found(request):
    return render(request, '404.html')

mysite/templates/blog/about.html
{% extends 'base.html' %}

{% block navigator %}
    <ul>
        <li><a href="{% url 'blog:index' %}">首页</a></li>
        <li><a href="{% url 'blog:archive_list' %}">归档</a></li>
        <li><a href="{% url 'blog:tag_list' %}">标签</a></li>
        <li><a href="#">分类</a></li>
		<li><a href="{% url 'blog:friends' %}">友链</a></li>
        <li><a href="{% url 'blog:about' %}" class="active">关于</a></li>
    </ul>
{% endblock navigator %}

{% block main %}
	{% for post in post_list %}
		<div class="post post-{{post.pk}}">
			<h2>{{post.title}}</h2>
			{% if post.avatar %}
				<div class="box alt">
					<div class="row uniform">
						<div class="12u$"><span class="image fit"><img src="{{post.avatar.url}}" alt="" /></span></div>
					</div>
				</div>
			{% endif %}
			<!--<h4>Left &amp; Right</h4>-->
			<p>{{post.body | safe}}</p>
		</div>
	{% endfor %}
{% endblock main %}

mysite/templates/blog/archive.html
{% extends 'base.html' %}

{% block navigator %}
    <ul>
        <li><a href="{% url 'blog:index' %}">首页</a></li>
        <li><a href="{% url 'blog:archive_list' %}" class="active">归档</a></li>
        <li><a href="{% url 'blog:tag_list' %}">标签</a></li>
        <li><a href="#">分类</a></li>
        <li><a href="{% url 'blog:friends' %}">友链</a></li>
        <li><a href="{% url 'blog:about' %}">关于</a></li>
    </ul>
{% endblock navigator %}

{% block main %}
<style>
    .archive-list li{
        display: inline-block;
        margin-right: 20px;
    }
    .archive-list li a {
        color: #5b5bf1;
        text-decoration: underline;
    }
    .archive-list li h2 {
        margin-bottom:5px;
    }
    .archive-list ul {
        margin-bottom:10px;
    }
</style>
    <div class="archive-list">
        {% for key,archive in archive_list.items %}
            <h2>{{key}}</h2>
            <ul>
                {% for item in archive %}
                    <li><a href="{% url 'blog:archives' item.year item.month %}" target="_self">{{item.year}}.{{item.month}}</a></li>
                {% endfor %}
            </ul>
        {% empty %}
        <li>暂无归档</li>
        {% endfor %}
    </div>
{% endblock main %}

mysite/templates/blog/detail.html
{% extends 'base.html' %}

{% load blog_tags %}

{% block navigator %}
<ul>
    <li><a href="{% url 'blog:index' %}">首页</a></li>
    <li><a href="{% url 'blog:archive_list' %}">归档</a></li>
    <li><a href="{% url 'blog:tag_list' %}">标签</a></li>
    <li><a href="#">分类</a></li>
    <li><a href="{% url 'blog:friends' %}">友链</a></li>
    <li><a href="{% url 'blog:about' %}">关于</a></li>
</ul>
{% endblock navigator %}

{% block main %}
<article class="post post-{{post.pk}}">
    <section>
        <h2 class="post-title">{{post.title}}</h2>
        <p class="post-info">字数：{{post.word_count}} · 阅读：{{post.views}} · 发布时间：{{post.create_time}}</p>
        <!--<div class="box alt">
            <div class="row uniform">
                <div class="12u$"><span class="image fit"><img src="" alt="" /></span></div>
            </div>
        </div>-->
        <!--<h4>Left &amp; Right</h4>-->
        <p>{{post.body | safe}}</p>
    </section>
</article>
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = "https://www.superbx.cn/post/{{post.pk}}/";  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = "{{post.pk}}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://lxl-blog.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock main %}

{% block newArticle %}
<!-- Mini Posts -->
<div class="new-post">
    <h2>最新文章</h2>
    {% get_recent_posts as recent_post_list %}
    <ul class="posts">
        {% for post in recent_post_list %}
        <li>
            <h3><a href="#">{{post.title}}</a></h3>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock newArticle %}

mysite/templates/blog/friends.html
{% extends 'base.html' %}

{% block navigator %}
    <ul>
        <li><a href="{% url 'blog:index' %}">首页</a></li>
        <li><a href="{% url 'blog:archive_list' %}">归档</a></li>
        <li><a href="{% url 'blog:tag_list' %}">标签</a></li>
        <li><a href="#">分类</a></li>
        <li><a href="{% url 'blog:friends' %}" class="active">友链</a></li>
        <li><a href="{% url 'blog:about' %}">关于</a></li>
    </ul>
{% endblock navigator %}

{% block main %}
<style>
    .friend-link {
        list-style: none;
    }
    .friend-link li{
        display: inline-block;
        margin-right:20px;
    }
    .friend-link li a {
        color: #0000aa;
        text-decoration: underline;
    }
</style>
<ul class="friend-link">
    {% for friend in friends_list %}
    <li>
        <a href="{{friend.site_url}}" title="{{friend.site_intro}}">{{friend.site_name}}</a>
    </li>
    {% endfor %}
</ul>
{% endblock main %}

mysite/templates/blog/index.html
{% extends 'base.html' %}

{% load blog_tags %}

{% block navigator %}
    <ul>
        <li><a href="{% url 'blog:index' %}" class="active">首页</a></li>
        <li><a href="{% url 'blog:archive_list' %}">归档</a></li>
        <li><a href="{% url 'blog:tag_list' %}">标签</a></li>
        <li><a href="#">分类</a></li>
        <li><a href="{% url 'blog:friends' %}">友链</a></li>
        <li><a href="{% url 'blog:about' %}">关于</a></li>
    </ul>
{% endblock navigator %}

{% block main %}
<!-- Post -->
    {% if error_msg %}
    <p>{{error_msg}}</p>
    {% endif %}
    {% for post in post_list %}
        <div class="post">
            <h2 title="{{post.title}}"><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
            <p class="post-desc">{{post.excerpt | safe}}</p>
            <div class="publish-time">{{post.create_time}} &nbsp; {{post.views}}次阅读数</div>
            {% if post.thumb %}
                <a href="{{post.get_absolute_url}}" class="image featured"><img src="{{post.thumb.url}}" alt=""/></a>
            {% endif %}
        </div>
    {% endfor %}


    {% if is_paginated %}
        <!-- Pagination -->
        <ul class="actions pagination">
            {% if first %}
                <li><a href="/">1</a></li>
            {% endif %}
            {% if left %}
                {% if left_has_more %}
                    <li><a href="?page={{page_number|add:'-3'}}">...</a></li>
                {% endif %}
                {% for i in left %}
                    <li><a href="?page={{i}}">{{i}}</a></li>
                {% endfor %}
            {% endif %}
                <li><a href="?page={{page_obj.number}}" class="active">{{page_obj.number}}</a></li>
            {% if right %}
                {% for i in right %}
                    <li><a href="?page={{i}}">{{i}}</a></li>
                {% endfor %}
                {% if right_has_more %}
                    <li><a href="?page={{page_number|add:3}}">···</a></li>
                {% endif %}
            {% endif %}
            {% if last %}
                    <li><a href="?page={{paginator.num_pages}}">{{paginator.num_pages}}</a></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock main %}

{% block intro %}
    {% get_user_profile as user_profile %}
    {% for user in user_profile %}
    <section id="intro">
        <a href="#" class="logo"><img src="{{user.avatar.url}}" alt=""/></a>
        <header>
            <h2>Superb-x</h2>
            <p>{{user.description}}</p>
        </header>
    </section>
    {% endfor %}
{% endblock intro %}

mysite/templates/blog/tags.html
{% extends 'base.html' %}

{% block navigator %}
    <ul>
        <li><a href="{% url 'blog:index' %}">首页</a></li>
        <li><a href="{% url 'blog:archive_list' %}">归档</a></li>
        <li><a href="{% url 'blog:tag_list' %}" class="active">标签</a></li>
        <li><a href="#">分类</a></li>
        <li><a href="{% url 'blog:friends' %}">友链</a></li>
        <li><a href="{% url 'blog:about' %}">关于</a></li>
    </ul>
{% endblock navigator %}

{% block main %}
<style>
    .tag-list .tag {
        display: inline-block;
        width:180px;
    }
    .tag-list .tag img {
        width:100%;
    }
</style>
    <div class="tag-list">
       {% for tag in tag_list %}
        <div class="tag"><a href="{% url 'blog:tag' tag.pk %}"><span class="image fit"><img src="{{tag.thumb.url}}" alt="" /></span></a></div>
       {% endfor %}
    </div>
{% endblock main %}